"""
ML training entry point — trains M1, M2, M3 (classifier + RUL), calibrates
thresholds, runs the novelty rank report, saves all weights.

Usage (from sih-project/):
    python3 -m ml.train [--device cpu|cuda|mps] [--epochs-m2 50] ...

Outputs (all under ml/weights/):
    m1_weights.pt               M1 correction MLP
    m1_scaler.json              operating-point normalisation
    m2_weights.pt               M2 LSTM autoencoder
    m2_threshold.json           calibrated anomaly threshold + persistence params
    m3_classifier_weights.pt    M3 fault classifier
    m3_rul_weights.pt           M3 two-headed RUL
    novelty_report.json         rank, singular values, null_space_dim, threshold

IMPORTANT — training data note
-------------------------------
These models were trained on SYNTHETIC residuals generated by ml/data/synthetic.py.
This data was NOT generated from BE-1's MVEM. It is operationally independent of
BE-1's current engine model state (which has a known collapsed air-path defect —
see docs/qa/known-issues.md, BE-1 Task 0).

Consequence: the models consume 11-dimensional residuals and were trained on all 11
dimensions. When BE-1 fixes rho1 and rho5 (currently on the 1e-3 sigma floor) and
the healthy dataset is regenerated, retrain M2 and M3 on the real data. The novelty
rank may also change on the sensitivity matrix — rerun the rank report then.

The demo MUST NOT train live. Weights are committed artefacts.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from ml.data.synthetic import SyntheticResidualDataset
from ml.m1_residual_estimator.model import M1ResidualEstimator, physics_loss
from ml.m2_autoencoder.model import LSTMAutoencoder, train_autoencoder, calibrate_threshold
from ml.m3_classifier.model import M3ClassifierModel, train_classifier, train_rul_head
from ml.m3_rul.model import RULModel
from ml.novelty.projection import NoveltyProjector, print_rank_report, null_space_direction
from ml.incidence import N_RESIDUALS, FAULT_NAMES

WEIGHTS_DIR = HERE / "weights"
WEIGHTS_DIR.mkdir(exist_ok=True)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="PRAMANA ML training")
    p.add_argument("--device",     default="cpu", choices=["cpu", "cuda", "mps"])
    p.add_argument("--epochs-m1",  type=int, default=40)
    p.add_argument("--epochs-m2",  type=int, default=50)
    p.add_argument("--epochs-m3",  type=int, default=60)
    p.add_argument("--batch-size", type=int, default=64)
    p.add_argument("--window-len", type=int, default=32)
    return p.parse_args()


# ── Novelty rank report ───────────────────────────────────────────────────

def run_novelty_report(healthy_rho: np.ndarray, weights_dir: Path) -> tuple:
    print("\n══ Novelty Rank Report ══")
    proj = NoveltyProjector()
    print_rank_report(proj)

    from ml.incidence import INCIDENCE
    ns_dir = null_space_direction(proj, seed=42)
    if np.linalg.norm(ns_dir) > 1e-9:
        # Per-cylinder expanded in-library test
        from ml.incidence import build_fault_matrix_expanded
        F_exp, labels = build_fault_matrix_expanded()
        idx = labels.index("injector_fouling_cyl2")
        sig = F_exp[:, idx] / np.linalg.norm(F_exp[:, idx])
        r_in  = proj.project(sig * 5.0)
        r_out = proj.project(ns_dir * 5.0)
        print(f"  in-library  injector_fouling_cyl2 × 5σ  → ν = {r_in.index:.4f}  (expect 0)")
        print(f"  out-library null-space dir × 5σ         → ν = {r_out.index:.4f}  (expect 1)")

    threshold = proj.calibrate_threshold(healthy_rho)

    report = {
        "effective_rank":       proj.effective_rank,
        "null_space_dim":       proj.null_space_dim,
        "singular_values":      [round(float(s), 4) for s in proj.S],
        "rank_tol":             proj.rank_tol,
        "n_expanded_columns":   int(proj.F_normalised.shape[1]),
        "threshold_99p5":       round(float(threshold), 4),
        "data_note": (
            "Rank computed on COARSE incidence matrix (entries 0,±1,±2). "
            "Must be recomputed on sensitivity matrix (Jacobian) before "
            "claiming this number on a slide. See novelty-detection.md."
        ),
    }
    out = weights_dir / "novelty_report.json"
    out.write_text(json.dumps(report, indent=2))
    print(f"  Saved → {out}")
    return proj, threshold


# ── M1 ────────────────────────────────────────────────────────────────────

def train_m1(args, dataset, weights_dir: Path) -> None:
    print("\n══ Training M1 — Physics-guided residual estimator ══")
    rng = np.random.default_rng(20)
    n   = len(dataset.healthy)
    u_train = rng.uniform(
        low= [2000, 900,  280, 0.003, 1.2,  60000, 1100, 340,    0, 40],
        high=[4000, 1300, 340, 0.012, 1.6, 140000, 1300, 410, 28000, 80],
        size=(n, 10)
    ).astype(np.float32)
    rho_target = np.zeros((n, N_RESIDUALS), dtype=np.float32)

    loader = DataLoader(
        torch.utils.data.TensorDataset(
            torch.from_numpy(u_train),
            torch.from_numpy(rho_target)
        ),
        batch_size=args.batch_size, shuffle=True
    )
    model  = M1ResidualEstimator(input_dim=10, hidden=64).to(args.device)
    opt    = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-5)
    crit   = torch.nn.MSELoss()

    for epoch in range(1, args.epochs_m1 + 1):
        model.train()
        total = 0.0
        for u_b, rho_b in loader:
            u_b, rho_b = u_b.to(args.device), rho_b.to(args.device)
            y_hat = model(u_b)
            loss  = crit(y_hat, rho_b) + physics_loss(y_hat, u_b)
            opt.zero_grad(); loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            total += loss.item() * u_b.size(0)
        if epoch % 10 == 0:
            print(f"  [M1] epoch {epoch}/{args.epochs_m1}  loss={total/n:.5f}")

    out = weights_dir / "m1_weights.pt"
    torch.save(model.state_dict(), out)
    print(f"  Saved → {out}")


# ── M2 ────────────────────────────────────────────────────────────────────

def train_m2(args, dataset, weights_dir: Path):
    print("\n══ Training M2 — LSTM Autoencoder ══")
    train_loader = DataLoader(dataset.healthy,     batch_size=args.batch_size, shuffle=True)
    val_loader   = DataLoader(dataset.healthy_val, batch_size=args.batch_size)

    model = LSTMAutoencoder(
        input_dim=N_RESIDUALS, hidden_dim=64, latent_dim=16,
        seq_len=dataset.window_len,
    )
    train_autoencoder(model, train_loader, epochs=args.epochs_m2, device=args.device)

    threshold = calibrate_threshold(model, val_loader, percentile=99.5, device=args.device)

    torch.save(model.state_dict(), weights_dir / "m2_weights.pt")
    (weights_dir / "m2_threshold.json").write_text(json.dumps({
        "threshold":   round(threshold, 6),
        "percentile":  99.5,
        "persistence": {"n": 4, "of": 5},
        "note": "99.5th pct of reconstruction error on held-out healthy data — never hand-picked",
    }, indent=2))
    print(f"  Saved → m2_weights.pt, m2_threshold.json")
    return model, threshold


# ── M3 classifier ─────────────────────────────────────────────────────────

def train_m3_classifier(args, dataset, weights_dir: Path):
    print("\n══ Training M3 — Classifier ══")
    loader = DataLoader(dataset.faulty, batch_size=args.batch_size, shuffle=True)

    model = M3ClassifierModel(
        n_fault_classes=dataset.n_fault_classes,
        input_dim=N_RESIDUALS,
    )
    train_classifier(model, loader, epochs=args.epochs_m3, device=args.device)

    # Quick training-set accuracy
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for x, y in loader:
            preds = model(x.to(args.device)).argmax(1).cpu()
            correct += (preds == y).sum().item()
            total   += y.size(0)
    print(f"  [M3-cls] train accuracy = {correct/total:.3f}")

    out = weights_dir / "m3_classifier_weights.pt"
    torch.save(model.state_dict(), out)
    print(f"  Saved → {out}")
    return model


# ── M3 RUL ────────────────────────────────────────────────────────────────

def train_m3_rul(args, dataset, weights_dir: Path):
    print("\n══ Training M3 — RUL heads ══")
    loader = DataLoader(dataset.faulty, batch_size=args.batch_size, shuffle=True)

    rul_model = RULModel(input_dim=N_RESIDUALS, seq_len=dataset.window_len)
    train_rul_head(rul_model, loader, epochs=args.epochs_m3, device=args.device)

    out = weights_dir / "m3_rul_weights.pt"
    torch.save(rul_model.state_dict(), out)
    print(f"  Saved → {out}")
    return rul_model


# ── Main ──────────────────────────────────────────────────────────────────

def main() -> None:
    args = parse_args()
    print(f"PRAMANA ML training  device={args.device}  window={args.window_len}")
    print("Training data: SYNTHETIC residuals (ml/data/synthetic.py)")
    print("NOT from BE-1's MVEM — models train on all 11 dims regardless of rho1/rho5 floor issue.")
    print()

    dataset = SyntheticResidualDataset(
        n_healthy=800, n_healthy_val=200,
        n_fault_per_class=300,
        window_len=args.window_len,
    )

    # Flat healthy residuals for novelty threshold calibration
    healthy_flat = np.array([
        dataset.healthy[i][0].numpy().mean(axis=0)
        for i in range(len(dataset.healthy))
    ])

    train_m1(args, dataset, WEIGHTS_DIR)
    train_m2(args, dataset, WEIGHTS_DIR)
    train_m3_classifier(args, dataset, WEIGHTS_DIR)
    train_m3_rul(args, dataset, WEIGHTS_DIR)
    run_novelty_report(healthy_flat, WEIGHTS_DIR)

    print("\n✓ All weights saved to", WEIGHTS_DIR)
    print("  Commit these — the demo must NOT train live.\n")
    print("  ⚠  Retrain M2 + M3 once BE-1 fixes rho1/rho5 and provides")
    print("     data/healthy_flights/*.parquet from the fixed MVEM.")


if __name__ == "__main__":
    main()
