"""
Profile validator — flags missing and assumed fields in an engine YAML.

Purpose: a profile generated by an AI agent (or typed by hand from a spec
sheet) may be missing fields the engine model requires, or may carry assumed
constants without that being stated. Either causes silent wrong answers rather
than loud failures. This script surfaces both.

Two categories of issue:
  ERROR   — field is required by the engine model and is absent. The engine
            will either crash or produce a nonsense result.
  WARNING — field is present but labelled 'assumed' (or carries no provenance).
            The system still runs, but any result that depends on this field
            is of lower confidence. Relevant if the profile is AI-generated.

Usage:
    # Validate the default engine:
    python -m twin.validate_profile

    # Validate a specific profile:
    python -m twin.validate_profile --engine rotax_914

    # Validate all profiles in config/:
    python -m twin.validate_profile --all

    # Non-zero exit code if any ERROR is found (useful in CI):
    python -m twin.validate_profile --strict
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

# Add backend to path when run as a script
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from twin.profiles import list_engines, load_engine_profile, DEFAULT_ENGINE

# ---------------------------------------------------------------------------
# Required field spec
# Each entry: (dot-path, description, condition)
# condition: callable(cfg) -> bool — only check this path if condition holds.
# None means always check.
# ---------------------------------------------------------------------------

_REQUIRED: list[tuple[list[str], str, Any]] = [
    # Each entry: ([canonical_path, ...aliases], description, condition)
    # If any path is present the check passes; canonical is listed first.
    # Identity
    (["profile.id"],          "engine ID (used to key all artifacts)",       None),
    (["profile.cycle"],       "combustion cycle (diesel | spark_ignition)",  None),
    (["profile.aspiration"],  "aspiration (turbocharged | naturally_aspirated)", None),
    # Geometry
    (["geometry.cylinders"],          "cylinder count",              None),
    (["geometry.displacement_m3"],    "displacement [m³]",           None),
    (["geometry.bore_m"],             "bore [m]",                    None),
    (["geometry.stroke_m"],           "stroke [m]",                  None),
    (["geometry.compression_ratio"],  "compression ratio",           None),
    (["geometry.strokes_per_cycle"],  "strokes per cycle",           None),
    # Ratings — accept both canonical (rated_*) and legacy Rotax (max_continuous_*)
    (["ratings.rated_power_kW",       "ratings.max_continuous_power_kW"], "rated/max-continuous power [kW]", None),
    (["ratings.rated_speed_rpm",      "ratings.max_continuous_rpm"],      "rated crank speed [rpm]",         None),
    (["ratings.max_continuous_rpm"],  "max continuous RPM",               None),
    (["ratings.critical_altitude_ft"],"critical altitude [ft] (0 for NA)",None),
    # Fuel
    (["fuel.Q_LHV_J_per_kg"],         "lower heating value [J/kg]",  None),
    (["fuel.AFR_stoich"],             "stoichiometric AFR",          None),
    (["fuel.rated_fuel_flow_kgps"],   "rated fuel flow [kg/s]",      None),
    # MVEM — volumetric efficiency
    (["mvem.volumetric_efficiency.correlation_c0"], "η_v correlation c0", None),
    (["mvem.volumetric_efficiency.correlation_c1"], "η_v correlation c1", None),
    (["mvem.volumetric_efficiency.correlation_c2"], "η_v correlation c2", None),
    (["mvem.volumetric_efficiency.correlation_c3"], "η_v correlation c3", None),
    # MVEM — combustion
    (["mvem.combustion.eta_i_nominal"], "indicated thermal efficiency", None),
    # MVEM — crankshaft
    (["mvem.crankshaft.inertia_kgm2"], "crankshaft inertia [kg·m²]", None),
    # MVEM — compressor (turbocharged only)
    (["mvem.compressor.impeller_diameter_m"],  "impeller diameter [m]",   lambda c: _is_turbo(c)),
    (["mvem.compressor.psi_max_design"],        "ψ_max (head ceiling)",    lambda c: _is_turbo(c)),
    (["mvem.compressor.phi_max_design"],        "φ_max (flow ceiling)",    lambda c: _is_turbo(c)),
    (["mvem.compressor.n_corr_design_rpm"],     "n_corr design [rpm]",     lambda c: _is_turbo(c)),
    (["mvem.compressor.efficiency_nominal"],    "η_c nominal",             lambda c: _is_turbo(c)),
    (["mvem.compressor.max_shaft_rpm"],         "turbo overspeed limit [rpm]", lambda c: _is_turbo(c)),
    # MVEM — turbine (turbocharged only)
    (["mvem.turbine.efficiency_nominal"],       "η_t nominal",             lambda c: _is_turbo(c)),
    (["mvem.turbine.mdot_ex_design_kgps"],      "turbine design exhaust flow [kg/s]", lambda c: _is_turbo(c)),
    # Limits
    (["limits.cht_C"],                  "CHT redline [°C]",             None),
    (["limits.oil_temp_C",    "limits.oil_temp_inlet_C"],   "oil temperature limit [°C]", None),
    (["limits.oil_pressure_bar.min_above_2500rpm",
      "limits.oil_pressure_bar.min_above_3500rpm"],         "min oil pressure [bar]",     None),
    # Propeller
    (["propeller.diameter_m"],          "propeller diameter [m]",      None),
    # Parity
    (["parity_paths.speed_density"],    "parity path availability",    None),
]

# Provenance values that mean "this field is uncertain"
_ASSUMED_PROVENANCE = {"assumed", "unverified_community", "calibrated"}


def _is_turbo(cfg: dict) -> bool:
    return cfg.get("profile", {}).get("aspiration", "turbocharged") != "naturally_aspirated"


def _get(cfg: dict, path: str) -> tuple[bool, Any]:
    """Traverse a dot-path. Returns (found, value)."""
    parts = path.split(".")
    node = cfg
    for p in parts:
        if not isinstance(node, dict) or p not in node:
            return False, None
        node = node[p]
    return True, node


def _provenance_of(cfg: dict, path: str) -> str | None:
    """Find provenance marker for a section: check the immediate parent block."""
    parts = path.split(".")
    # Check section-level provenance (e.g. geometry.provenance, mvem.compressor.provenance)
    for depth in range(len(parts), 0, -1):
        parent_path = ".".join(parts[:depth])
        found, val = _get(cfg, parent_path)
        if found and isinstance(val, dict):
            prov = val.get("provenance")
            if prov:
                return str(prov)
    return None


def validate(cfg: dict) -> tuple[list[str], list[str]]:
    """
    Returns (errors, warnings).
    errors   — required fields missing; engine will crash or produce nonsense.
    warnings — fields present but with assumed/uncertain provenance.
    """
    errors: list[str] = []
    warnings: list[str] = []

    for paths, description, condition in _REQUIRED:
        if condition is not None and not condition(cfg):
            continue
        # Accept if ANY alias is present
        found_path = None
        found_value = None
        for path in paths:
            found, value = _get(cfg, path)
            if found and value is not None:
                found_path = path
                found_value = value
                break
        if found_path is None:
            canonical = paths[0]
            errors.append(f"  MISSING  {canonical}  ({description})")
            continue
        # Check provenance of the found path
        prov = _provenance_of(cfg, found_path)
        if prov in _ASSUMED_PROVENANCE:
            warnings.append(f"  ASSUMED  {found_path}  [{prov}]  ({description})")

    return errors, warnings


def report(engine_id: str, cfg: dict, strict: bool = False) -> bool:
    """Print validation report. Returns True if no errors."""
    errors, warnings = validate(cfg)
    cycle = cfg.get("profile", {}).get("cycle", "?")
    aspiration = cfg.get("profile", {}).get("aspiration", "?")
    print(f"\n{'='*60}")
    print(f"  Engine: {engine_id}  ({cycle}, {aspiration})")
    print(f"{'='*60}")
    if not errors and not warnings:
        print("  OK — no errors or assumed fields found.")
        return True
    if errors:
        print(f"  {len(errors)} ERROR(S) — engine will fail or produce wrong results:")
        for e in errors:
            print(e)
    if warnings:
        print(f"  {len(warnings)} WARNING(S) — assumed fields (lower confidence if AI-generated):")
        for w in warnings:
            print(w)
    if errors:
        print(f"\n  RESULT: INVALID — fix errors before running the engine model.")
        return False
    print(f"\n  RESULT: VALID with {len(warnings)} assumed field(s) — usable but provisional.")
    return True


def main() -> None:
    ap = argparse.ArgumentParser(description="Validate PRAMANA engine profile(s)")
    ap.add_argument("--engine", default=None, help="engine id or filename (default: $PRAMANA_ENGINE)")
    ap.add_argument("--all", action="store_true", help="validate all profiles in config/")
    ap.add_argument("--strict", action="store_true",
                    help="exit non-zero if ANY error found (useful for CI)")
    args = ap.parse_args()

    all_ok = True
    if args.all:
        engines = list_engines()
        if not engines:
            print("No engine profiles found in config/.")
            sys.exit(1)
        for eid, path in engines.items():
            with open(path, encoding="utf-8") as f:
                cfg = yaml.safe_load(f)
            ok = report(eid, cfg, args.strict)
            all_ok = all_ok and ok
    else:
        engine = args.engine or DEFAULT_ENGINE
        cfg = load_engine_profile(engine)
        eid = cfg.get("profile", {}).get("id", engine)
        ok = report(eid, cfg, args.strict)
        all_ok = ok

    if args.strict and not all_ok:
        sys.exit(1)
    print()


if __name__ == "__main__":
    main()
