/**
 * PRAMANA telemetry types — generated by hand from docs/spec/telemetry-schema.md.
 *
 * These mirror the FROZEN schema. If BE-1 changes a field, it changes here too,
 * and the change gets announced before it is pushed. A silent rename on Day 3
 * costs the team more than the feature was worth.
 */

/** Cylinders of the engine that is open. A live binding: chooseEngine() sets it before any panel renders, and the
 *  panels are remounted (keyed by engine) so nothing keeps a stale count. 4 until an engine is chosen. */
export let N_CYL = 4;
export function setNCyl(n: number) { N_CYL = Math.max(1, Math.round(n)); }

/** Per-cylinder values are ALWAYS length N_CYL, always the same ordering.
 *  0-indexed in code, 1-indexed in the UI. Cylinder 2 in the demo script is [1]. */
export type PerCylinder = number[];

// ---------------------------------------------------------------------------
// Lane 2 — SLOW (10-50 Hz, downlinked). The raw engine channel set.
// This is PS component B verbatim.
// ---------------------------------------------------------------------------
export interface SlowFrame {
  schema: 'pramana.slow.v1';
  t: number;                    // seconds since mission start, NOT wall clock
  engine_id: 'A' | 'B';
  seq: number;

  rpm: number;
  map_hPa: number;              // intake manifold absolute pressure
  iat_K: number;
  cht_C: PerCylinder;
  egt_C: PerCylinder;
  oil_press_bar: number;
  oil_temp_C: number;
  fuel_flow_kgps: number;
  /** null = not modelled (served as a frozen constant before 2026-09-24). */
  fuel_rail_bar: number | null;
  lambda: number;               // wideband UEGO — parity Path 3 depends on this
  turbo_rpm: number;
  comp_out_p_hPa: number;
  comp_out_T_K: number;
  inj_timing_deg: number | null;       // PS component B — null: not modelled
  bus_voltage_V: number | null;        // PS component B — null: not modelled
  alternator_A: number | null;         // PS component B — null: not modelled
  throttle_pct: number;
  vib_rms_g: PerCylinder | null;   // null: no vibration model

  altitude_ft: number;
  tas_mps: number;
  oat_K: number;
  /** Ambient (compressor inlet) pressure. Parity Path 2 needs this and OAT:
   *  the compressor map is evaluated at INLET conditions, so it cannot be
   *  closed from manifold-side channels alone. A genuinely separate
   *  transducer from map_hPa, which is what keeps rho1 independent. */
  p_amb_hPa: number;
  /** Drivetrain and air data — sensed channels added with the reduction
   *  gearbox and constant-speed propeller (config/sensors.yaml). tas_mps
   *  above is the air-data reading now, not a constant. */
  prop_rpm: number;
  /** Blade angle from pitch-actuator feedback; null on a fixed-pitch profile. */
  blade_angle_deg: number | null;
  /** Gearbox oil temperature; null on a profile with no gearbox oil node. */
  gearbox_oil_C: number | null;
  /** Coolant temperature — THE production channel on a liquid-cooled diesel.
   *  Null on a profile with no coolant loop (the air-cooled Rotax). */
  coolant_temp_C: number | null;
}

// ---------------------------------------------------------------------------
// Fast-lane FEATURES — what actually crosses the bandwidth boundary.
// Raw 20 kHz vibration never leaves the airframe.
// ---------------------------------------------------------------------------
export interface FastFeatures {
  schema: 'pramana.fastfeat.v1';
  t: number;
  engine_id: 'A' | 'B';
  /** THE misfire discriminant. Each cylinder fires once per 720 deg of crank
   *  rotation, so a single-cylinder defect appears at 0.5 engine order.
   *  Zero for a balanced engine. */
  order_0p5_mag: number;
  order_0p5_phase_deg: number | null;  // null: not modelled
  order_1p0_mag: number | null;
  order_2p0_mag: number | null;
  knock_intensity: PerCylinder;
  vib_band_rms: { lo_0_500: number; mid_500_5k: number; hi_5k_20k: number } | null;
}

// ---------------------------------------------------------------------------
// Lane 3 — HEALTH (1 Hz). THE FRONTEND'S ONLY CONTRACT.
// Everything on screen derives from this message.
// ---------------------------------------------------------------------------

/** Parity residual vector. Nominally ZERO, operating-point invariant by
 *  construction, normalised by the healthy-data sigma — so units are "sigmas". */
export interface ResidualVector {
  rho1_sd_vs_comp: number | null;    // speed-density vs compressor map
  rho2_sd_vs_lambda: number | null;  // speed-density vs fuel/lambda
  rho3_sd_vs_restr: number | null;   // null when the path is unavailable
  rho4_energy: number;               // first-law closure
  rho5_power: number;                // propeller-as-dynamometer
  rho6_9_cyl_dev: PerCylinder;       // per-cylinder thermal deviation
  rho10_oil: number;
  rho11_ripple: number;              // 0.5-order magnitude
}

export interface Estimate {
  value: number;
  sigma: number;
}
export interface PerCylEstimate {
  value: PerCylinder;
  sigma: PerCylinder;
}

/** UKF-estimated health parameters. These ARE the health indicators, in
 *  physical units, each with a covariance. "Compressor efficiency scale 0.87
 *  +/- 0.02, down from 0.94" is a statement an engineer can dispute.
 *  "Health score 0.71" is not. */
export interface HealthParams {
  eta_v_scale: Estimate;     // induction and sealing — ring wear enters here
  eta_c_scale: Estimate;     // compressor — invisible at sea level
  hA_scale: Estimate;        // cooling
  cd_inj: PerCylEstimate;    // injector discharge coefficient, per cylinder
  f_fric_scale: Estimate;    // friction — bearing wear
  /** LIVE only — health parameters the engine model gained since v1. */
  rad_eff_scale?: Estimate;  // radiator effectiveness
  cool_pump_scale?: Estimate; // coolant pump flow
  oil_pump_scale?: Estimate; // oil pump delivery
  fuel_rail_scale?: Estimate; // fuel supply (filter)
}

/** Analytical redundancy. If a quantity is recoverable along several paths,
 *  any one path supplies it when its sensor is absent. DRDO asks for virtual
 *  sensing by name — these are the payoff. */
export interface VirtualSensors {
  peak_cyl_press_bar: PerCylinder | null;   // null: no in-cylinder pressure model
  knock_margin_deg: number | null;           // null: not modelled
  turbo_shaft_rpm_est: number;
  comb_efficiency: PerCylinder | null;      // null: not modelled
  air_mass_flow_kgps: number;
  brake_power_kW: number;
  bsfc_g_per_kWh: number;    // DEGRADED, not the book figure — drives the PNR
}

export interface AnomalyState {
  score: number | null;
  threshold: number | null;  // 99.5th pct of healthy held-out. Never hand-picked.
  persistence: { n: number; of: number; met: boolean };
}

export type FaultId =
  | 'healthy'
  | 'unknown'
  | 'injector_fouling'
  | 'injection_misfire'
  | 'ring_wear'
  | 'oil_pump_wear'
  | 'turbo_degradation'
  | 'cooling_fouling'
  | 'coolant_pump_degradation'
  | 'detonation'
  | 'fuel_filter_clog'
  | 'bearing_wear'
  | 'map_sensor_drift'
  | 'egt_sensor_drift'
  | 'cht_sensor_drift'
  | 'lambda_sensor_drift';

export interface FaultHypothesis {
  fault: FaultId;
  cylinder: number | null;   // 0-indexed; null for engine-wide faults
  p: number;
  source: 'classifier+matrix' | 'matrix' | 'classifier';
}

export interface Diagnosis {
  top: FaultHypothesis[];
  /** THE differentiator. Drives the demo's 3:00 beat. */
  is_sensor_fault: boolean;
  /** true => structure cannot separate the hypotheses; active diagnosis armed */
  ambiguous: boolean;
  probe: ActiveProbe | null;
  /** Faults the structure measurably cannot separate from the top call. */
  inseparable_from?: FaultId[];
  /** true: the ML layer is down and there is NO diagnosis this tick. */
  unavailable?: boolean;
}

/** Active diagnosis: when structure cannot resolve, the system commands a small
 *  bounded perturbation and tests the GAIN of the response, not its level.
 *  A sensor's constant bias cancels identically from the alternating component. */
export interface ActiveProbe {
  running: boolean;
  cylinder: number;
  amplitude_pct: number;     // stays inside FADEC trim authority, +/-3 to 5%
  elapsed_s: number;
  gain_estimate: number;     // ~kappa*G0 under H1, ~G0 under H2
  log_likelihood_ratio: number;
  decision: 'pending' | 'component_fault' | 'sensor_fault';
}

export interface RulEstimate {
  component: string;
  /** Damage-rate integration forward. NULL when BE-1's damage integrator has
   *  supplied no rate yet — the head has not reported, which is different from
   *  it reporting an unbounded life. */
  physics_h: number | null;
  network_h: number | null;  // severity-trend head, p50 of the Monte Carlo
  p10_h: number | null;
  p50_h: number | null;
  p90_h: number | null;
  /** The CONSERVATIVE of the two heads. null: no engine fault diagnosed, or
   *  no redline predicted inside the fault's modelled range. */
  reported_h: number | null;
  heads_disagree: boolean;   // disagreement beyond the interval is itself a warning
}

/** PS asks for reliability ENHANCEMENT, not monitoring. Three options with
 *  quantified risk, and the cost of the safe one — because reliability advice
 *  that ignores mission value is ignored advice. */
export interface MissionDecision {
  /** null while the ML layer is unavailable — never a guess. */
  p_complete_continue: number | null;
  p_complete_derate: number | null;
  p_complete_rtb: number | null;
  derate_cost_min_on_station: number | null;   // null: needs an airframe model
  recommended: 'continue' | 'derate' | 'rtb' | null;
  recommended_power_pct: number | null;
  recommended_boost_hPa: number | null;
  method?: 'monte_carlo';
  m?: number;
  assumed_fields?: string[];
  assumed_inputs?: Record<string, number | boolean>;
  /** P(no redline yet) at 10 %, 20 % … 100 % of the remaining mission if it
   *  continues — straight from the Monte Carlo draws. */
  survival_continue?: number[] | null;
  point_of_no_return_s: number;   // from remaining fuel and DEGRADED bsfc
}

export type LimitsState = 'green' | 'caution' | 'exceeded';

/** Novelty detection — see docs/spec/novelty-detection.md.
 *  OPTIONAL: the GCS hides the confidence channel rather than showing a wrong
 *  number when the backend does not publish it yet. */
export interface NoveltyState {
  index: number;              // nu = ||rho_perp|| / ||rho||, in [0,1]
  residual_norm: number;
  unexplained_norm: number;
  threshold: number;          // 99.5th pct of nu on held-out healthy data
  exceeded: boolean;
  effective_rank: number;     // rank(F). If null_space_dim is 0 the claim dies.
  null_space_dim: number;
  /** Per-residual unexplained component, for the explain drawer. */
  unexplained?: number[];
}

export interface TwinConfidence {
  value: number;              // 1 - nu, clipped
  basis: string;
  note: string;
}

export interface HealthFrame {
  schema: 'pramana.health.v1';
  t: number;
  engine_id: 'A' | 'B';
  rho: ResidualVector;
  /** null while the ML layer is unavailable. */
  theta: HealthParams | null;
  virtual: VirtualSensors;
  anomaly: AnomalyState;
  diagnosis: Diagnosis;
  rul: RulEstimate;
  mission: MissionDecision;
  novelty?: NoveltyState;
  twin_confidence?: TwinConfidence;
  /** What a THRESHOLD system would be showing right now. Keep it on screen:
   *  the contrast is the whole argument. */
  limits_state: LimitsState;
  /** LIVE only: whether the ML layer produced this frame's diagnosis. */
  ml_status?: { active: boolean; reason: string | null; commissioned?: string | null };
  /** LIVE only: the extended residuals, by name. */
  rho_ext?: Record<string, number | null>;
  /** LIVE only: the evidence behind the current call — the recent residual
   *  window and the MEASURED signature of the fault being named. */
  explain?: { features: string[]; live: number[]; signature: number[];
             signature_key: string; match_cosine: number } | null;
  /** LIVE only: schema fields that are null because nothing models them. */
  unmodelled?: string[];
}

// ---------------------------------------------------------------------------
// A single tick of the mission: everything the UI needs at one instant.
// ---------------------------------------------------------------------------
export interface MissionTick {
  slow: SlowFrame;
  /** The second engine. Twin-engined platform, so this is a free reference
   *  channel: common-mode variation cancels exactly in the difference. */
  slowB?: SlowFrame;
  fast: FastFeatures;
  health: HealthFrame;
  /** What the twin PREDICTED the slow channels would read. The gap between
   *  this and `slow` is the entire product. */
  predicted: Pick<SlowFrame, 'egt_C' | 'cht_C' | 'oil_press_bar' | 'map_hPa' | 'fuel_flow_kgps'>;
}

// ---------------------------------------------------------------------------
// Residual display metadata — used by the heatmap and the explain drawer.
// ---------------------------------------------------------------------------
export interface ResidualMeta {
  key: string;
  label: string;
  detail: string;
}

export const RESIDUAL_ROWS: ResidualMeta[] = [
  { key: 'rho1', label: 'ρ₁  air: speed-density vs compressor', detail: 'Path 1 − Path 2' },
  { key: 'rho2', label: 'ρ₂  air: speed-density vs fuel/λ', detail: 'Path 1 − Path 3' },
  { key: 'rho3', label: 'ρ₃  air: speed-density vs restriction', detail: 'unavailable — engine is unthrottled' },
  { key: 'rho4', label: 'ρ₄  energy closure', detail: 'first law: fuel in = work + exhaust + heat' },
  { key: 'rho5', label: 'ρ₅  power closure', detail: 'propeller as a calibrated dynamometer' },
  { key: 'rho6', label: 'ρ₆  cyl 1 thermal deviation', detail: 'vs conditional mean across cylinders' },
  { key: 'rho7', label: 'ρ₇  cyl 2 thermal deviation', detail: 'vs conditional mean across cylinders' },
  { key: 'rho8', label: 'ρ₈  cyl 3 thermal deviation', detail: 'vs conditional mean across cylinders' },
  { key: 'rho9', label: 'ρ₉  cyl 4 thermal deviation', detail: 'vs conditional mean across cylinders' },
  { key: 'rho10', label: 'ρ₁₀ oil pressure model', detail: 'vs speed- and temperature-dependent model' },
  { key: 'rho11', label: 'ρ₁₁ 0.5-order crank ripple', detail: 'zero for a balanced engine' },
];

/** Flatten the residual vector to the 11-row display order. */
export function residualRow(rho: ResidualVector): (number | null)[] {
  return [
    rho.rho1_sd_vs_comp,
    rho.rho2_sd_vs_lambda,
    rho.rho3_sd_vs_restr,
    rho.rho4_energy,
    rho.rho5_power,
    rho.rho6_9_cyl_dev[0],
    rho.rho6_9_cyl_dev[1],
    rho.rho6_9_cyl_dev[2],
    rho.rho6_9_cyl_dev[3],
    rho.rho10_oil,
    rho.rho11_ripple,
  ];
}

export const FAULT_LABELS: Record<FaultId, string> = {
  healthy: 'Healthy',
  unknown: 'Unrecognised excitation',
  injector_fouling: 'Injector fouling',
  // Diesel terms: a compression-ignition engine has no ignition system, and
  // 'pre-ignition' / 'vapour lock' are petrol-engine phenomena.
  injection_misfire: 'Misfire (combustion failure)',
  ring_wear: 'Piston ring wear / blow-by',
  oil_pump_wear: 'Oil leak / pump wear',
  turbo_degradation: 'Turbocharger degradation',
  cooling_fouling: 'Radiator fouling',
  coolant_pump_degradation: 'Coolant pump degradation',
  detonation: 'Combustion knock',
  fuel_filter_clog: 'Fuel filter clog',
  bearing_wear: 'Bearing wear',
  map_sensor_drift: 'MAP sensor drift',
  egt_sensor_drift: 'EGT sensor drift',
  cht_sensor_drift: 'CHT sensor drift',
  lambda_sensor_drift: 'λ sensor drift',
};

/** Component faults vs instrumentation faults — the line in the incidence
 *  matrix. Everything below it is a sensor, not an engine. */
export const SENSOR_FAULTS: FaultId[] = [
  'map_sensor_drift',
  'egt_sensor_drift',
  'cht_sensor_drift',
  'lambda_sensor_drift',
];
